Repository fantastic-octo-garbanzo/FNotepad, pull requests merged in 2021-02, with the labels that each got.

#43 Removed abbrevation
  FNotepadEN.java
Labels: bug

#41 Changed folder structure
  FileFilter/FileFilterDE.java
  FileFilter/FileFilterEN.java
  FileOperation/FileOperationDE.java
  FileOperation/FileOperationEN.java
  FindDialog/FindDialogDE.java
  FindDialog/FindDialogEN.java
  FontChooser/FontChooserDE.java
  FontChooser/FontChooserEN.java
  LookAndFeelMenu/LookAndFeelMenuDE.java
  LookAndFeelMenu/LookAndFeelMenuEN.java
  MyFileFilterDE.java
  MyFileFilterEN.java
Labels: documentation

#49 Tab setting
  NotePads/FNotepadDE.java
Labels: enhancement

#54 Choice -> JComboBox
  NotePads/FNotepad.java
Labels: bug, enhancement

#55 Helppage and return button
  NotePads/FNotepadDE.java
  NotePads/FNotepadEN.java
Labels: bug, documentation, enhancement

#53 Added new feature: Opened files are in new windows.
  FileOperation/FileOperationDE.java
Labels: bug, enhancement

#56 Update items of JComboBox
  NotePads/FNotepad.java
Labels: documentation

#58 Windowopen
  FileOperation/FileOperationDE.java
  FileOperation/FileOperationEN.java
  NotePads/FNotepadDE.java
  NotePads/FNotepadEN.java
Labels: documentation

#62 Count bug fix
  NotePads/FNotepadDE.java
  NotePads/FNotepadEN.java
Labels: bug

#63 Hilfe datei einbinden
  META-INF/MANIFEST.MF
  NotePads/FNotepadDE.java
  NotePads/FNotepadEN.java
  bin/Help.txt
  bin/Hilfe.txt
Labels: documentation

#70 Removed unnecessary code
  FileFilter/FileFilterDE.java
  FileFilter/FileFilterEN.java
  FileOperation/FileOperationDE.java
  FileOperation/FileOperationEN.java
  FindDialog/FindDialogDE.java
  FontChooser/FontChooserDE.java
  FontChooser/FontChooserEN.java
  LookAndFeelMenu/LookAndFeelMenuDE.java
  LookAndFeelMenu/LookAndFeelMenuEN.java
  NotePads/FNotepad.java
  NotePads/FNotepadDE.java
  NotePads/FNotepadEN.java
Labels: documentation

#69 Added beta rpm, src rpm and deb packages
  release/latest/FNotepad-1.3.3-1.fc33.noarch.rpm
  release/latest/FNotepad-1.3.3-1.fc33.src.rpm
  release/latest/FNotepad-1.3.3.deb
Labels: enhancement
