Repository fantastic-octo-garbanzo/FNotepad, pull requests merged in 2021-03, with the labels that each got.

#77 Hilfe datei einbinden
  NotePads/FNotepadDE.java
Labels: bug

#79 Help file
  NotePads/FNotepadDE.java
  NotePads/FNotepadEN.java
  NotePads/FNotepadIT.java
Labels: bug, documentation

#81 Hilfe datei einbinden
  MenuConstants/MenuConstantsDE.java
  MenuConstants/MenuConstantsEN.java
  MenuConstants/MenuConstantsIT.java
  NotePads/FNotepadDE.java
  NotePads/FNotepadEN.java
  NotePads/FNotepadIT.java
Labels: enhancement
